import sys
import json
from typing import Dict, Any
from .utils import clean_header

def gen_template(config: Dict[str, Any], policy_version: str) -> str:
    """Generates a Markdown template from loaded rules."""
    lines = ["# AI Project Spec (Generated by nod)", "", f"> Policy: {policy_version}\n"]
    for name, data in config.get("profiles", {}).items():
        lines.append(f"---\n## Profile: {data.get('badge_label', name)}\n")
        for req in data.get("requirements", []):
            header = req.get("label") or clean_header(req['id'])
            lines += [f"### {header}", f"<!-- {req.get('remediation', 'Fill section')} -->"]
            if req.get("must_contain"):
                lines += ["<!-- Subsections: -->"] + req["must_contain"]
            lines.append("TODO: Add details...\n")
    return "\n".join(lines)

def gen_context(config: Dict[str, Any], policy_version: str, ignored: list, fmt: str = "context") -> str:
    """Generates a System Prompt context for AI agents."""
    lines = []
    if fmt == "cursor":
        lines.append("You are an AI programming assistant. You must adhere to the following compliance constraints when generating code or specifications.\n")
    elif fmt == "windsurf":
        lines.append("You are Cascade. Follow these mandatory compliance rules in all generation tasks.\n")

    lines += ["# SYSTEM COMPLIANCE CONSTRAINTS", f"POLICY: {policy_version}", "MANDATORY CONSTRAINTS:\n"]
    
    for name, data in config.get("profiles", {}).items():
        reqs = [r for r in data.get("requirements", []) if r["id"] not in ignored]
        flags = [f for f in data.get("red_flags", []) if f["pattern"] not in ignored]
        
        if not reqs and not flags:
            continue
            
        lines.append(f"## {data.get('badge_label', name)}")
        
        if reqs:
            lines.append("### REQUIRE:")
            for r in reqs:
                name = r.get("label") or clean_header(r['id'])
                lines.append(f"- {name}: {r.get('remediation','')}")
        
        if flags:
            lines.append("### FORBID:")
            for f in flags:
                name = f.get("label") or f"PATTERN '{f['pattern']}'"
                lines.append(f"- {name}: {f.get('remediation','')}")
        lines.append("")
        
    return "\n".join(lines)

def gen_schema(config: Dict[str, Any], policy_version: str) -> str:
    """Generates a JSON Schema representation of the active policy."""
    schema = {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "nod Compliance Policy",
        "version": policy_version,
        "description": "Active compliance rules loaded by nod.",
        "type": "object",
        "properties": {
            "profiles": {
                "type": "object",
                "properties": {}
            }
        }
    }

    for name, data in config.get("profiles", {}).items():
        profile_schema = {
            "type": "object",
            "description": data.get('badge_label', name),
            "properties": {
                "requirements": {"type": "array", "items": {"type": "string"}},
                "red_flags": {"type": "array", "items": {"type": "string"}}
            }
        }
        
        # Populate specific requirements as enums/examples
        reqs = [r.get("label") or clean_header(r['id']) for r in data.get("requirements", [])]
        if reqs:
            profile_schema["properties"]["requirements"]["examples"] = reqs
            
        schema["properties"]["profiles"]["properties"][name] = profile_schema

    return json.dumps(schema, indent=2)

def apply_fix(path: str, results: Dict[str, Any]) -> None:
    """Appends missing sections to the target file."""
    # Logic to determine target file (if directory passed, create nod-compliance.md)
    import os
    tgt = path if os.path.isfile(path) else os.path.join(path, "nod-compliance.md")
    
    try:
        with open(tgt, "a", encoding="utf-8") as f:
            f.write("\n\n<!-- nod: auto-fix -->\n")
            cnt = 0
            for data in results.values():
                miss = [c for c in data["checks"] if c["status"] == "FAIL" and c.get("type") != "red_flag" and not c.get("id").startswith("XRef")]
                if miss:
                    f.write(f"\n## Missing: {data['label']}\n")
                    for m in miss:
                        header = m.get("label") or clean_header(m['id'])
                        f.write(f"\n### {header}\n")
                        if m.get("control_id"):
                            f.write(f"> Ref: {m['control_id']}\n")
                        f.write(f"<!-- {m.get('remediation')} -->\nTODO: Details.\n")
                        cnt += 1
        print(f"✅ Patched {tgt} (+{cnt})")
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
